<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle(Zend_Registry::get('config')->site->name);
echo $this->doctype(); ?>
<html>
<head>
<?php
// Add scripts to view
$this->headScript()->appendFile($this->baseUrl()."/js/jquery-1.7.1.min.js");
$this->headScript()->appendFile($this->baseUrl()."/js/less-1.1.5.min.js");

// Add stylesheets to view
$this->headLink()->appendStylesheet($this->baseUrl().'/lib/bootstrap.less','all', null, array('rel' => 'stylesheet/less', 'type' => 'text/css'));
$this->headLink()->appendStylesheet($this->baseUrl().'/quiz.admin.less','all', null, array('rel' => 'stylesheet/less', 'type' => 'text/css'));

// Create array for the body's classes.
$arr_body_classes = array();

// Interogate our class from Zend, add them to arr_body_classes
$obj_zend_instance = Zend_Controller_Front::getInstance();
$request = Zend_Controller_Front::getInstance()->getRequest();
foreach($request->getParams() as $key => $value){
	if(is_object($value)){
		continue;
	}
	$arr_body_classes[] = strtolower(@ereg_replace("[^A-Za-z0-9 -.]", "", $value));
}


?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
<?php echo $this->headScript(); ?>
<meta name='viewport' content='width=device-width,minimum-scale=1,maximum-scale=1,user-scalable=no' />
</head>
<body class="<?php echo implode(" ",$arr_body_classes);?>">
<?php include("layout.header.phtml");?>
<?php echo $this->layout()->content; ?>	
<?php include("layout.footer.phtml");?>
</body>
</html>
